# -*- coding: utf-8 -*-
"""colab基本操作.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HI6vPPtZtQWGKYTmEl3oYiDjHBhe41-U
"""

# https://colab.research.google.com/drive/1lB_rx79_pqEY7JCCeKylq84PtMvnxhw3?usp=sharing#scrollTo=UT0TEPRS7KF6

# check data in the path
!ls

# check allocated GPU type
!nvidia-smi

# 連結google drive
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# 在雲端建立新資料夾
# %cd /content/drive/MyDrive 
#change directory to google drive
!mkdir ML2022 #make a directory named ML2022
# %cd ./ML2022 
#change directory to ML2022

# Download the file with file_id "sUr1x-GhJ_80vIGzVGEqFUSDYfwV50YW", and rename it to pikachu.png
!gdown --id '11zyOyAK-TKxgfMk7ADZypEwUtG6twrdE' --output chiwawa.jpg