# -*- coding: utf-8 -*-
"""linear regression multiple variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12bFbWHfO352rrAMhKcd8BgIK_t38kie1
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
import math

df = pd.read_csv("homeprice.csv")
df

bedroom_med = math.floor(df.bedroom.median())
df.bedroom = df.bedroom.fillna(bedroom_med)
df

reg = linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df.price)

result = reg.predict([[3000,3,40]])
result