# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Al6y2LdR9mTGLdIz-E7S8mT0giFY7VIG
"""

# price = m * area + b
# m = slope(gradient)
# b = intercept
# price = dependent variable
# area = independent variable

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv("data.csv")

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area', fontsize=20)
plt.ylabel('price', fontsize=20)
plt.scatter(df.area, df.price, color = 'red', marker = '+')

reg = linear_model.LinearRegression()
reg.fit(df[['area']], df.price)

reg.predict([[3300]])

x = 3300
m = reg.coef_
b = reg.intercept_
y = m * x + b
print(y)



d = pd.read_csv('data_predict.csv')
d

# 寫入資料至d(自動加新欄位price)
p = reg.predict(d)
d['price'] = p

# 匯出結果
d.to_csv('data_predict2.csv', index=False)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area', fontsize=20)
plt.ylabel('price', fontsize=20)
plt.scatter(d.area, d.price, color = 'red', marker = '+')
plt.plot(d.area, d.price, color = 'blue')

